package entity;

/**
 * Central manifest of all self-registering map entity classes.
 *
 * The body of init() is generated automatically at compile time by
 * EntityMacro.buildInit().  It scans every .hx file in src/entity/,
 * finds classes that declare a static "__reg" field (the self-registration
 * convention), and emits a reference expression for each one.
 *
 * HOW TO ADD A NEW ENTITY TYPE
 * -----------------------------
 *   1. Create your entity class anywhere in src/entity/:
 *        @:keep
 *        private static var __reg = EntityRegistry.register("MyClass", (x,y) -> new MyClass(x, y));
 *   2. That's it. The macro picks it up automatically on the next build.
 *
 * Call EntityClasses.init() once before parsing any map data.
 */
@:build(EntityMacro.buildInit())
class EntityClasses {

    /** Body is generated by EntityMacro — do not edit manually. */
    public static function init():Void {}
}
